version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=dev_jwt_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
    depends_on:
      - mongodb

  catalog-service:
    build: ./catalog-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=catalog
      - JWT_PUBLIC_KEY=dev_jwt_public_key
    depends_on:
      - postgres

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongodb-data:
  postgres-data:
