version: '3.8'

services:
  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb+srv://sathira:dilshara224@universitytimetable.tydk7eb.mongodb.net/universityTimeTable_db?retryWrites=true&w=majority
      - JWT_SECRET=fdab12533795d6b429e3e94ac7ebae3d0488578e13cda4c1aac6ea68b31e9299
      - JWT_REFRESH_SECRET=8151a689124116f6dfd1d925ff90814a36a89dde5d05ac2db113121b7f1ff420c56db0269b91cba53e2d58dc184ec6f0da557337cc2d7d521c95ba562682f8c9
      - JWT_EXPIRE=15m
      - REFRESH_TOKEN_EXPIRE=7d
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - microservices-network

  # Product Catalog Service
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb+srv://sathira:dilshara224@universitytimetable.tydk7eb.mongodb.net/universityTimeTable_db?retryWrites=true&w=majority
      - JWT_SECRET=fdab12533795d6b429e3e94ac7ebae3d0488578e13cda4c1aac6ea68b31e9299
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - microservices-network

  # MongoDB Database (shared by both services)
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb-data:
