AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Cluster for microservices'

Resources:
  # ECS Cluster
  MicroservicesCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: microservices-cluster
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1

  # ECS Task Execution Role (for pulling images, etc.)
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  ClusterName:
    Description: The name of the ECS cluster
    Value: !Ref MicroservicesCluster
    Export:
      Name: !Sub "${AWS::StackName}-ClusterName"

  ECSTaskExecutionRoleArn:
    Description: The ARN of the ECS task execution role
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSTaskExecutionRoleArn"
