# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Auth Service dependencies
      run: |
        cd auth-service
        npm ci
        
    - name: Install Product Service dependencies
      run: |
        cd product-service
        npm ci
        
    - name: Run linting
      run: |
        cd auth-service
        npm run lint || echo "No linting configured"
        cd ../product-service
        npm run lint || echo "No linting configured"
    
    - name: Run tests
      run: |
        cd auth-service
        npm test || echo "No tests configured"
        cd ../product-service
        npm test || echo "No tests configured"
        
    - name: Build Docker images
      run: docker-compose build
